"""Initial schema with User, CVUpload, JobSearch, and SavedJob tables

Revision ID: 430ef9481c03
Revises: 
Create Date: 2025-10-29 19:33:20.814608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430ef9481c03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=512), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=False),
    sa.Column('oauth_id', sa.String(length=255), nullable=False),
    sa.Column('default_region', sa.String(length=100), nullable=True),
    sa.Column('default_job_source', sa.String(length=50), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth', 'users', ['oauth_provider', 'oauth_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cv_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('profile_data', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_uploads_user_id'), 'cv_uploads', ['user_id'], unique=False)
    op.create_table('saved_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('job_url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_reasons', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('application_status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_jobs_saved_at'), 'saved_jobs', ['saved_at'], unique=False)
    op.create_index(op.f('ix_saved_jobs_user_id'), 'saved_jobs', ['user_id'], unique=False)
    op.create_table('job_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cv_upload_id', sa.Integer(), nullable=True),
    sa.Column('job_source', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('jobspy_sites', sa.String(length=255), nullable=True),
    sa.Column('total_jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_above_threshold', sa.Integer(), nullable=True),
    sa.Column('average_match_score', sa.Float(), nullable=True),
    sa.Column('highest_match_score', sa.Float(), nullable=True),
    sa.Column('search_duration_seconds', sa.Float(), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cv_upload_id'], ['cv_uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_searches_searched_at'), 'job_searches', ['searched_at'], unique=False)
    op.create_index(op.f('ix_job_searches_user_id'), 'job_searches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_searches_user_id'), table_name='job_searches')
    op.drop_index(op.f('ix_job_searches_searched_at'), table_name='job_searches')
    op.drop_table('job_searches')
    op.drop_index(op.f('ix_saved_jobs_user_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_saved_at'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index(op.f('ix_cv_uploads_user_id'), table_name='cv_uploads')
    op.drop_table('cv_uploads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_oauth', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
